[project]
name = "paper-adass-xxxv"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "polars>=1.37.0",
    "ruff>=0.14.11",
    "scipy>=1.17.0",
]
